CREATE TABLE livro (
    id SERIAL PRIMARY KEY,
    titulo VARCHAR(100) NOT NULL,
    autor VARCHAR(100) NOT NULL,
    preco DECIMAL(8, 2),
    estoque INTEGER DEFAULT 0,
    ativo BOOLEAN DEFAULT TRUE
)